(()=>{'use strict';
const SELLER='https://josephsocialmedia2-spec.github.io/immobili-in-zona/seller_radar_auto/data/giro_acquisizione.csv';
const EDIL='./data/radar_edilizio.json';
const LOCAL_CONTACTS='f1TerritoryPrivateContacts';const LOGS='f1TerritoryLogs';
const KM={'susa':0,'mompantero':1.4,'meana di susa':1.9,'gravere':3.2,'giaglione':3.5,'venaus':4.3,'mattie':5.2,'chiomonte':5.8,'novalesa':6.8,'bussoleno':7.2,'chianocco':9.1,'moncenisio':9.2,'san giorio di susa':9.8,'exilles':10.8,'bruzolo':11.3,'san didero':12.4,'salbertrand':15.3};
let route=[],edilDb={opportunities:[],backlog:[],contacts:[]},edilSignals=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,' ').replace(/[^a-z0-9/ ]+/g,' ').replace(/\s+/g,' ').trim();
const phone=s=>String(s||'').replace(/[^0-9+]/g,'').trim();
const safe=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const excludedComune=s=>norm(s)==='sant ambrogio di torino';
const km=x=>KM[norm(x.comune||x.COMUNE)]??Infinity;
function parseCSV(t){t=t.replace(/^\uFEFF/,'');let rows=[],r=[],c='',q=false;for(let i=0;i<t.length;i++){let x=t[i];if(q){if(x==='"'&&t[i+1]==='"'){c+='"';i++}else if(x==='"')q=false;else c+=x}else if(x==='"')q=true;else if(x===','){r.push(c);c=''}else if(x==='\n'){r.push(c);rows.push(r);r=[];c=''}else if(x!=='\r')c+=x}if(c||r.length){r.push(c);rows.push(r)}if(rows.length<2)return[];const h=rows.shift().map(x=>x.trim());return rows.filter(x=>x.some(Boolean)).map(x=>Object.fromEntries(h.map((k,i)=>[k,(x[i]||'').trim()]))) }
function street(v){let s=norm(v).replace(/\b\d{5}\b/g,'').replace(/\btorino\b/g,'');return s.replace(/\s+\d+[a-z]?\/?\d*\s*$/,'').trim()}
function civic(v){const m=norm(v).match(/(?:^|\s)(\d+[a-z]?\/?\d*)\s*$/);return m?m[1]:''}
function maps(addr,comune){return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent([addr,comune,'TO Italia'].filter(Boolean).join(', '))}
function practiceKey(s){const n=norm(s);const m=n.match(/(?:pdc|scia|cila|scagi|albo|conformita|suap)[^0-9]*(\d+\s*\/\s*\d{4})/i);return m?m[1].replace(/\s+/g,''):n}
function unqualifiedEdilAddress(v){return !String(v||'').trim()||/DA APPROFONDIRE|DA VERIFICARE/i.test(String(v||''))}
function obviousEdilNoise(x){const t=norm([x.atto,x.tipo,x.descrizione].filter(Boolean).join(' '));const core=/\b(pdc|scia|cila|scagi)\b|permesso di costruire|pratica edilizia|edilizia privata|agibilita|cambio di destinazione|accertamento conformita/.test(t);const bad=/documento pec|deposito atti|soget|riscossione|assistenza legale|stragiudiziale|fornitura di stabilizzato|manutenzione straordinaria della strada/.test(t);return bad&&!core}
function buildEdil(){const raw=[...(edilDb.opportunities||[]),...(edilDb.backlog||[])];const seen=new Set;edilSignals=[];for(const x of raw){if(excludedComune(x.comune)||km(x)>20||obviousEdilNoise(x))continue;const key=norm(x.comune)+'|'+practiceKey(x.atto||x.pratica||x.descrizione);if(seen.has(key))continue;seen.add(key);edilSignals.push(x)}edilSignals.sort((a,b)=>km(a)-km(b)||String(b.date||'').localeCompare(String(a.date||'')))}
function routeEdil(r){const town=norm(r.COMUNE);const addr=street(r.DOVE_ANDRE);return edilSignals.filter(x=>{if(norm(x.comune)!==town||unqualifiedEdilAddress(x.indirizzo))return false;const xa=street(x.indirizzo);return !!(xa&&addr&&(xa===addr||xa.includes(addr)||addr.includes(xa)))}).slice(0,3)}
function localContacts(){const x=safe(LOCAL_CONTACTS,[]);return Array.isArray(x)?x:[]}
function logs(){const x=safe(LOGS,[]);return Array.isArray(x)?x:[]}
function matchedContacts(r){const rs=street(r.DOVE_ANDRE),rc=civic(r.DOVE_ANDRE);return localContacts().filter(c=>{const cs=street(c.via||c.address||'');return cs&&rs&&(cs===rs||cs.includes(rs)||rs.includes(cs))}).map(c=>({...c,_exact:rc&&norm(rc)===norm(c.civico||civic(c.address||''))})).sort((a,b)=>Number(b._exact)-Number(a._exact))}
function professionalContacts(){const practices=edilSignals.map(x=>practiceKey(x.atto||x.pratica||x.descrizione)).filter(Boolean);return (edilDb.contacts||[]).filter(c=>phone(c.telefono)&&!excludedComune(c.comune)&&practices.some(p=>{const cp=practiceKey(c.pratica||'');return cp&&(p.includes(cp)||cp.includes(p)||p.split('/')[0]===cp.split('/')[0])})).sort((a,b)=>String(a.priorita||'').localeCompare(String(b.priorita||'')))}
function linkedSignalForProfessional(c){const cp=practiceKey(c.pratica||'');return edilSignals.find(x=>{const p=practiceKey(x.atto||x.pratica||x.descrizione);return cp&&p&&(p.includes(cp)||cp.includes(p)||p.split('/')[0]===cp.split('/')[0])})}
function renderStats(){const l=logs(),p=professionalContacts(),streetN=route.reduce((n,r)=>n+matchedContacts(r).length,0);$('#sStops').textContent=route.length;$('#sEdil').textContent=edilSignals.length;$('#sPhones').textContent=streetN+p.length;$('#sHot').textContent=l.filter(x=>['HOT','WARM'].includes(x.priorita)).length;$('#sFollow').textContent=l.filter(x=>x.data_followup&&x.stato!=='CHIUSO').length;$('#sLogs').textContent=l.length}
function renderMission(){const r=route[0],e=edilSignals.find(x=>x.indirizzo&&!/DA APPROFONDIRE|DA VERIFICARE/i.test(x.indirizzo||''))||edilSignals[0];if(r){$('#missionTitle').textContent='Lavora '+r.COMUNE+' · '+r.DOVE_ANDRE;$('#missionBody').textContent='Seller Radar: '+(r.COSA_CERCO||'segnale territoriale')+' · score '+(r.SCORE||'—');$('#missionWhere').textContent=r.COMUNE+' — '+r.DOVE_ANDRE;$('#missionWhy').textContent=(r.COSA_CERCO||'Verifica il segnale sul territorio.')+(r.SELLER_SIGNAL?' · Segnale: '+r.SELLER_SIGNAL:'');$('#missionActions').innerHTML=`<a class="btn primary" target="_blank" href="${maps(r.DOVE_ANDRE,r.COMUNE)}">MAPPA</a><button class="btn" data-prefill="${esc(r.COMUNE)}|${esc(r.DOVE_ANDRE)}|OSSERVAZIONE|${esc(r.FONTE||'Seller Radar')}">REGISTRA</button>`}else if(e){$('#missionTitle').textContent='Qualifica Radar Edilizio · '+(e.comune||'territorio');$('#missionWhere').textContent=(e.comune||'')+' — '+(e.indirizzo||'DA APPROFONDIRE');$('#missionWhy').textContent=e.azione||'Apri la fonte e qualifica indirizzo, tecnico e impresa.';$('#missionActions').innerHTML=e.source_url?`<a class="btn primary" target="_blank" href="${esc(e.source_url)}">APRI FONTE</a>`:''}else{$('#missionTitle').textContent='Nessuna missione automatica disponibile';$('#missionWhere').textContent='—';$('#missionWhy').textContent='Seller Radar e Radar Edilizio non hanno prodotto una fermata utilizzabile.';$('#missionActions').innerHTML=''}
$('#missionEdil').innerHTML=edilSignals.length?edilSignals.slice(0,6).map(edilCard).join(''):'<div class="empty">Nessun segnale edilizio entro il perimetro operativo.</div>';bindPrefill()}
function edilCard(x){const verified=x.indirizzo&&!/DA APPROFONDIRE|DA VERIFICARE/i.test(x.indirizzo||'');return`<article class="item"><div class="itemtop"><div><b>${esc(x.comune||'')} · ${esc(x.tipo||x.classe||'RADAR EDILIZIO')}</b><div class="meta">${esc(x.atto||'')} · ${esc(x.date||'')}</div></div><span class="tag ${x.priorita==='ALTA'?'gold':''}">${esc(x.priorita||'MEDIA')}</span></div><div class="meta"><b>INDIRIZZO:</b> ${esc(x.indirizzo||'DA APPROFONDIRE')}<br><b>AZIONE:</b> ${esc(x.azione||'Qualificare fonte, indirizzo, tecnico e impresa.')}</div><div class="row">${x.source_url?`<a class="btn" target="_blank" href="${esc(x.source_url)}">FONTE</a>`:''}${verified?`<a class="btn primary" target="_blank" href="${maps(x.indirizzo,x.comune)}">MAPPA</a><button class="btn" data-prefill="${esc(x.comune)}|${esc(x.indirizzo)}|CANTIERE|FATTO DOCUMENTATO · Radar Edilizio">REGISTRA VERIFICA</button>`:''}</div></article>`}
function renderGiro(){const box=$('#giroList');box.innerHTML=route.length?route.map((r,i)=>{const ed=routeEdil(r),mc=matchedContacts(r);return`<article class="item"><div class="itemtop"><div><span class="tag">FERMATA ${i+1}</span><h3>${esc(r.COMUNE)} — ${esc(r.DOVE_ANDRE)}</h3></div><b>${km({comune:r.COMUNE}).toFixed(1)} km</b></div><div class="meta"><b>PERCHÉ:</b> ${esc(r.COSA_CERCO||'Verifica segnale territoriale')}<br><b>FONTE:</b> ${esc(r.FONTE||'Seller Radar')}<br><b>NUMERI VIA:</b> ${mc.length} · <b>RADAR EDILIZIO:</b> ${ed.length}</div>${ed.length?`<div class="warning">Radar Edilizio collegato: ${ed.map(x=>esc(x.atto||x.tipo)).join(' · ')}</div>`:''}<div class="row"><a class="btn primary" target="_blank" href="${maps(r.DOVE_ANDRE,r.COMUNE)}">MAPPA</a><button class="btn" data-go="citofono">CITOFONO</button><button class="btn" data-go="porta">PORTA A PORTA</button><button class="btn" data-prefill="${esc(r.COMUNE)}|${esc(r.DOVE_ANDRE)}|OSSERVAZIONE|${esc(r.FONTE||'Seller Radar')}">REGISTRA</button></div></article>`}).join(''):'<div class="empty">Nessuna fermata Seller Radar operativa entro 20 km da Susa.</div>';bindGo();bindPrefill()}
function renderField(target,type){const box=$(target);box.innerHTML=route.length?route.map(r=>{const ed=routeEdil(r);const motive=type==='CITOFONO'?'Aprire una conversazione e verificare solo informazioni pertinenti.':'Lavorare questa via con una motivazione reale e dichiarata.';return`<article class="item"><div class="itemtop"><div><b>${esc(r.COMUNE)} — ${esc(r.DOVE_ANDRE)}</b><div class="meta">${esc(r.COSA_CERCO||motive)}</div></div><span class="tag">${type.replace('_',' ')}</span></div>${ed.length?`<div class="warning"><b>RADAR EDILIZIO:</b> ${ed.map(x=>esc((x.tipo||'atto')+' · '+(x.atto||''))).join('<br>')}<br>Usalo come segnale da verificare, non come prova di vendita.</div>`:''}<div class="row"><a class="btn primary" target="_blank" href="${maps(r.DOVE_ANDRE,r.COMUNE)}">MAPPA</a><button class="btn" data-prefill="${esc(r.COMUNE)}|${esc(r.DOVE_ANDRE)}|${type}|${esc(r.FONTE||'Territorio / Seller Radar')}">REGISTRA ESITO</button></div></article>`}).join(''):'<div class="empty">Nessuna via assegnata.</div>';bindPrefill()}
function renderPhones(){const streetRows=[];for(const r of route){for(const c of matchedContacts(r))streetRows.push({r,c})}$('#streetPhones').innerHTML=streetRows.length?streetRows.map(({r,c})=>`<article class="item"><div class="itemtop"><div><b>${esc(c.nome||c.name||'Contatto')}</b><div class="meta">${esc(r.COMUNE)} · ${esc(r.DOVE_ANDRE)} · ${c._exact?'CIVICO ESATTO':'STESSA VIA'}</div></div><span class="tag">VIA</span></div><div class="phone">${esc(c.telefono||c.phone)}</div><div class="meta"><b>PERCHÉ:</b> contatto associato alla via lavorata.<br><b>FONTE:</b> ${esc(c.fonte||c.source||'import locale')}<br><b>OBIETTIVO:</b> verificare la situazione o svolgere il follow-up previsto. Non chiamare se manca una base lecita o se è NON CONTATTARE.</div><div class="row"><a class="btn primary" href="tel:${phone(c.telefono||c.phone)}">CHIAMA</a><button class="btn" data-prefill="${esc(r.COMUNE)}|${esc(r.DOVE_ANDRE)}|TELEFONATA|${esc(c.fonte||c.source||'Import locale')}">REGISTRA ESITO</button></div></article>`).join(''):'<div class="empty">Nessun numero locale associato alle vie. Importa CSV/XLSX: resta solo sul dispositivo.</div>';
const pros=professionalContacts();$('#professionalPhones').innerHTML=pros.length?pros.map(c=>{const s=linkedSignalForProfessional(c);return`<article class="item"><div class="itemtop"><div><b>${esc(c.nome||c.studio_azienda||'Professionista')}</b><div class="meta">${esc(c.ruolo||'Addetto ai lavori')} · ${esc(c.studio_azienda||'')}</div></div><span class="tag gold">RADAR EDILIZIO</span></div><div class="phone">${esc(c.telefono)}</div><div class="meta"><b>PERCHÉ:</b> recapito professionale pubblico collegato a ${esc(c.pratica||'una pratica edilizia')}.<br><b>SEGNALAZIONE:</b> ${esc(s?.comune||'')} ${esc(s?.atto||'')}<br><b>OBIETTIVO:</b> relazione F1 Local Network / verifica tecnica pertinente. Nessuna richiesta di dati privati di proprietari.<br><b>FONTE:</b> Radar Edilizio F1.</div><div class="row"><a class="btn primary" href="tel:${phone(c.telefono)}">CHIAMA</a><button class="btn" data-prefill="${esc(s?.comune||c.comune||'')}|${esc(s?.indirizzo||'')}|TELEFONATA|FATTO DOCUMENTATO · Radar Edilizio">REGISTRA ESITO</button></div></article>`}).join(''):'<div class="empty">Nessun recapito professionale pubblico collegato alle pratiche operative.</div>';bindPrefill();renderStats()}
function renderLogs(){const l=logs();$('#logList').innerHTML=l.length?l.map(x=>`<article class="item"><div class="itemtop"><div><b>${esc(x.comune||'')} · ${esc(x.via||'')}</b><div class="meta">${esc(x.data)} · ${esc(x.tipo_attivita)} · ${esc(x.operatore||'')}</div></div><span class="tag">${esc(x.livello)} / ${esc(x.attendibilita)}</span></div><div class="meta"><b>FONTE:</b> ${esc(x.fonte)}<br><b>INFORMAZIONE:</b> ${esc(x.informazione)}<br><b>PRIORITÀ:</b> ${esc(x.priorita)} · <b>STATO:</b> ${esc(x.stato)}${x.data_followup?'<br><b>FOLLOW-UP:</b> '+esc(x.data_followup):''}${x.azione_successiva?'<br><b>PROSSIMA AZIONE:</b> '+esc(x.azione_successiva):''}</div></article>`).join(''):'<div class="empty">Nessuna attività ancora registrata su questo dispositivo.</div>';renderStats()}
function openLog(pref={}){$('#logModal').classList.add('on');$('#fOperatore').value=pref.operatore||localStorage.getItem('f1TerritoryOperator')||'';$('#fTipo').value=pref.tipo||'OSSERVAZIONE';$('#fComune').value=pref.comune||'';$('#fVia').value=pref.via||'';$('#fCivico').value=pref.civico||civic(pref.via||'');$('#fPalazzo').value='';$('#fFonte').value=pref.fonte||'';$('#fInfo').value='';$('#fLivello').value='N0';$('#fAttend').value='F1';$('#fDiretto').value='NO';$('#fPriorita').value='INFORMATION ONLY';$('#fNext').value='';$('#fFollow').value='';$('#fStato').value='APERTO';$('#fNote').value=''}
function saveLog(){const record={id:'ACT-'+Date.now(),data:new Date().toISOString(),operatore:$('#fOperatore').value.trim(),comune:$('#fComune').value.trim(),via:$('#fVia').value.trim(),civico:$('#fCivico').value.trim(),palazzo:$('#fPalazzo').value.trim(),tipo_attivita:$('#fTipo').value,fonte:$('#fFonte').value.trim(),informazione:$('#fInfo').value.trim(),livello:$('#fLivello').value,attendibilita:$('#fAttend').value,contatto_diretto:$('#fDiretto').value,priorita:$('#fPriorita').value,azione_successiva:$('#fNext').value.trim(),data_followup:$('#fFollow').value,stato:$('#fStato').value,note:$('#fNote').value.trim()};if(!record.fonte||!record.informazione){alert('FONTE e INFORMAZIONE sono obbligatorie.');return}if(record.livello==='N2'&&record.contatto_diretto!=='SI'){alert('N2 PROSPECT richiede contatto diretto. Se l’informazione è indiretta, usa N1/NOTIZIA.');return}if(record.stato==='NON_CONTATTARE')record.azione_successiva='NESSUN ULTERIORE CONTATTO COMMERCIALE';const l=logs();l.unshift(record);save(LOGS,l);localStorage.setItem('f1TerritoryOperator',record.operatore);$('#logModal').classList.remove('on');renderLogs();renderStats()}
async function importContacts(file){const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array'}),found=[];for(const sn of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:''});let hi=-1,map={};for(let i=0;i<Math.min(30,rows.length);i++){const h=rows[i].map(norm);const idx=names=>h.findIndex(v=>names.includes(v));const p=idx(['telefono','phone','tel','cellulare']),v=idx(['via','indirizzo','address']);if(p>=0&&v>=0){hi=i;map={nome:idx(['nome','name','nominativo']),cognome:idx(['cognome','surname']),p,v,civ:idx(['civico','numero civico']),com:idx(['comune','city']),fonte:idx(['fonte','source']),note:idx(['note'])};break}}if(hi<0)continue;for(let i=hi+1;i<rows.length;i++){const r=rows[i],tel=phone(r[map.p]);if(!tel)continue;const via=String(r[map.v]||'').trim();if(!via)continue;found.push({id:'LOCAL-'+tel.replace(/\D/g,''),nome:[map.nome>=0?r[map.nome]:'',map.cognome>=0?r[map.cognome]:''].filter(Boolean).join(' ').trim(),telefono:tel,via,civico:map.civ>=0?String(r[map.civ]||'').trim():'',comune:map.com>=0?String(r[map.com]||'').trim():'',fonte:map.fonte>=0?String(r[map.fonte]||'').trim():'Import locale',note:map.note>=0?String(r[map.note]||'').trim():'',imported_at:new Date().toISOString()})}}if(!found.length)throw Error('Non trovo almeno le colonne TELEFONO e VIA');const old=localContacts(),m=new Map;[...old,...found].forEach(c=>m.set(phone(c.telefono)||c.id,c));save(LOCAL_CONTACTS,[...m.values()]);renderPhones();renderStats();alert('Numeri importati localmente: '+found.length+'. Non sono stati pubblicati su GitHub.')}
function bindPrefill(){$$('[data-prefill]').forEach(b=>b.onclick=()=>{const [comune,via,tipo,fonte]=b.dataset.prefill.split('|');openLog({comune,via,tipo,fonte})})}
function showScreen(name){$$('.screen').forEach(x=>x.classList.toggle('on',x.dataset.page===name));$$('[data-screen]').forEach(x=>x.classList.toggle('on',x.dataset.screen===name));location.hash=name;if(name==='telefonate')renderPhones();if(name==='registro')renderLogs()}
function bindGo(){$$('[data-go]').forEach(b=>b.onclick=()=>showScreen(b.dataset.go))}
async function loadData(){try{const [s,e]=await Promise.all([fetch(SELLER+'?v='+Date.now(),{cache:'no-store'}),fetch(EDIL+'?v='+Date.now(),{cache:'no-store'})]);if(!s.ok||!e.ok)throw new Error('Feed territorio non raggiungibile');const seller=parseCSV(await s.text());edilDb=await e.json();route=seller.filter(r=>/VAI IN ZONA/i.test(r.AZIONE||'')&&!/DA VERIFICARE/i.test(r.DOVE_ANDRE||'')&&!excludedComune(r.COMUNE)&&km({comune:r.COMUNE})<=20).sort((a,b)=>km({comune:a.COMUNE})-km({comune:b.COMUNE})||(+b.SCORE||0)-(+a.SCORE||0));buildEdil();renderAll()}catch(e){$('#missionTitle').textContent='Errore caricamento dati';$('#missionBody').textContent=e.message}}
function renderAll(){renderMission();renderGiro();renderField('#citofonoList','CITOFONO');renderField('#portaList','PORTA_A_PORTA');renderPhones();renderLogs();renderStats();bindGo()}
$$('[data-screen]').forEach(a=>a.onclick=e=>{e.preventDefault();showScreen(a.dataset.screen)});bindGo();$('#newLog').onclick=()=>openLog();$('#closeModal').onclick=()=>$('#logModal').classList.remove('on');$('#saveLog').onclick=saveLog;$('#logModal').onclick=e=>{if(e.target.id==='logModal')$('#logModal').classList.remove('on')};$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{await importContacts(f)}catch(err){alert('Import non riuscito: '+err.message)}e.target.value=''};$('#clearPrivate').onclick=()=>{if(confirm('Eliminare i numeri importati localmente su questo dispositivo?')){localStorage.removeItem(LOCAL_CONTACTS);renderPhones();renderStats()}};const initial=(location.hash||'#missione').slice(1);if(['missione','giro','citofono','porta','telefonate','registro'].includes(initial))showScreen(initial);loadData();
})();